on: [push]

jobs:
  tag:
    runs-on: ubuntu-latest
    name: Bump version and create tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Get new version
        id: version
        uses: paulhatch/semantic-version@v5.0.2

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.version.outputs.version_tag}}"
