on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Bump version and create tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Get new version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          use_branches: true
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: info
        run: |
          echo Version: ${{ steps.version.outputs.version }}
          echo Increment: ${{ steps.version.outputs.increment }}
          echo Version tag: ${{ steps.version.outputs.version_tag }}

      ## this is where we will build it using ${{ steps.version.outputs.version_tag}}
      ## so we only create the tag if the build is successful
    outputs:
      version_tag: ${{ steps.version.outputs.version_tag }}

  deploy:
    needs: [build]
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ needs.build.outputs.version_tag}}"
